version: "2"
services:
    node9:
        build:
            context: .
            dockerfile: Dockerfile
        user: "node"
        working_dir: /app
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=5000
            - DEBUG=redovisa:*
        volumes:
            - ./:/app
        ports:
            - "5000:5000"
        links:
            - mongodb
        command: "npm start"

    mongodb:
        image: mongo
        container_name: "mongodb_redovisa"
        environment:
            - MONGO_DATA_DIR=/data/db
        ports:
            - 27017:27017
        command: mongod
